### ISSUE TITLE
ast and pretty print correctness

### ISSUE THREAD

**Issue by CostaArmenUniMelb** [CostaArmenUniMelb/CantParseUs#1]
Hey guys, 
I think I've covered all possible types (operators, statements, declarations etc.) and print scenarios in the ast and pretty print. 

Please review the types in snack_ast and the, 'test' function in snack_pprint.ml (too large to copy and paste here). The output from the test is the following,

proc proc1 (val bool declIdentBool1, ref int declIdentInt2)
     bool declIdentBool1;
     int declIdentInt2;
     float declIdentFloat3;
     float declIdentFloatArray3[1..2,1..3];

     assignIdent1 := (not true or false);
     assignIdent2 := 1;
     assignIdent3 := declIdentBool1;
     assignIdent4 := 1 + -2.1;
     assignIdentFloatArray5[1 - 2,5] := 10.1;
     assignIdentFloatArray6[assignIdent2] := 10.1;
     assignIdentFloatArray6[] := 10.1;
     read readIdent3;
     write -assignIdent1;
     proc1(assignIdent1,-9.2);
     proc1();
     while 1 do
         if 1 <= 2.1 then
             read readIdent3;
             write -assignIdent1;
         else
             if true != (not false) then
                 read readIdent3;
                 write -assignIdent1;
             fi
         fi
     od
end

proc proc2 ()
     read readIdent3;
end

You can see from the above that there are nested whiledo/ifthen/ifthenelse functions, multiple procedures in the program, multi dim array declarations, multi dim array assignments, empty/non-empty param procedure calls/declarations, binary/unary arithmetic and boolean expressions, and read write statements.

**Comment by CostaArmenUniMelb** [comment]
github has formatted it weird. 

![test output](https://cloud.githubusercontent.com/assets/21965932/24320755/b0b1bb4e-118f-11e7-924c-2628a3ae37d5.PNG)

**Comment by poomnewgen** [comment]
I found the incorrect printing for expressions. Please try to run the program with the example "logical.snick". The printer removed all parentheses so it's wrong. It's supposed to keep all necessary parentheses.

**Comment by CostaArmenUniMelb** [comment]
It wasn't clear to me at the time so I skipped over it and forgot about it. Have you fixed it? or do you want me to look into it? If so, I'll do that tomorrow.

**Comment by poomnewgen** [comment]
Nope, I haven't fixed it yet. You should take a look at it by the due date. 👍  It might take time fixing this.

**Comment by CostaArmenUniMelb** [comment]
Ok no worries i'll do it tomorrow

**Comment by CostaArmenUniMelb** [comment]
Hey guys,
In restricting the pretty print to only have necessary parenthesis, do you think the following strategy works? 

Create the parse tree and wherever there is a parent binary expression that has the same precedence as a child binary expression, that child binary expression requires parenthesis surrounding it. Consider the following generalised example, 

given "Expr1 binop0 Expr2" 
where "Expr1 = Expr3 binop1 Expr4"
and "Expr2 = Expr5 binop2 Expr6"
(or in expanded form: "Expr3 binop1 Expr4 binop0 Expr5 binop2 Expr6")
if "binop0 has the same precedence as binop1"
then "Expr1 requires surrounding parenthesis i.e. (Expr3 binop1 Expr4)"
if "binop0 has the same precedence as binop2"
then "Expr2 expression requires surrounding parenthesis i.e. (Expr5 binop2 Expr6)"
resulting in "(Expr3 binop1 Expr4) binop0 (Expr5 binop2 Expr6)"

In the example given in the spec,
"((x) - (y - (4*z)))" 
becomes
"x - (y - 4 * z)"

Using the generalised form described above,
Expr1 = x
Expr2 = y - 4 * z
binop0 = -
Expr5 = y
binop2 = -
Expr6 = 4 * z
since binop0 and binop2 have the same precedence, Expr2 requires parenthesis. 

"same precedence" equivalence sets are {add,sub} and {mul,div}, which are the sets of tokens in the %left tokens within the parser doc. Since the rest of the operators are non-associative, not having parenthesis does not change the meaning.

Is this correct? I ran a few examples and the results are ok but I think I need more to confirm this is correct. Can you guys run a few examples?

**Comment by CostaArmenUniMelb** [comment]
Just to let you know, I also,

1. added List.rev in a few places in the parser as statements in the if the else expression and procedure invocation params were coming out in reverse order. 

2. Added whitespace between params in procedure calls. 

I went through all the test cases and the output from our system matches the output from the test cases.

**Comment by poomnewgen** [comment]
Thanks for the fixing. How could I miss this 😄 . 

I'm not sure what you mean by "create a parse tree". The output is an AST so  I don't think you need to create another tree. Maybe you just create a function and pass some parameters such as the current Expression and Parent Expression.

Basically, I think what you said about the priority is correct for only the given case. 

e.g. *,/ have the same precedence but you don't need to add parenthesis

Ex: 3*(4/5)*4  or (3+4)-5+(30-4)
We need to remove all of them.

So, there are many cases should be concerned. For example.
x-(5-3)

Exp1 =x-(5-3)  Binop = -
Exp2 = 5-3   Binop = -  

Let's current Exp = Exp2 and the parent of Exp2 is Exp1

In this case, Parent Exp operation is - and Current Exp is - and Current Exp is on RHS of the parent. For this case, we need to add parenthesis to the current Exp.

However, if the input is 
(x-5)-3
Exp1 =(x-5)-3  Binop = -
Exp2 = x-5   Binop = -  
the Parent Exp operation is - , Current Exp operation is - but the Current Exp is on LHS of the parent. For this case, we don't need any parenthesis.

And there are other cases and we have to make sure that it works in all cases.

**Comment by CostaArmenUniMelb** [comment]
I'll look into this after work tonight (after 6-7pm). 

As a quick response, I meant create a parse tree to aid in the demonstration of the concept, not the implementation. Sorry, I didn't explain that clearly. 

To summarize what you've explained, 
1. No need for {mul,div} parenthesis
2. Only apply the rule for RHS children, not LHS children. This is due to the right to left evaluation ordering?

**Comment by poomnewgen** [comment]
1.Yes and no, in some cases you need () for mul,div e.g. (5-6)*30
2. that depends on the cases.

You need to list all possible cases first.
e.g the one in the instruction and the two examples I gave to you
Try to draw trees on a paper for each mathematical expression and generate the condition for each case.
![image](https://cloud.githubusercontent.com/assets/20880484/24787696/419ec90e-1bad-11e7-95c2-c3696d7ade12.png)

**Comment by CostaArmenUniMelb** [comment]
found a nice explanation on how to do it.
http://codinghighway.com/2015/05/25/down-with-redundant-parenthesis/

**Comment by poomnewgen** [comment]
Good. Have you finished this yet?

**Comment by CostaArmenUniMelb** [comment]
Started last night but had some personal stuff to attend to so continuing this morning. Im doing what you said to do, which is writing out all possible combinations and testing to see if parenthesis make a difference to the RHS child using a simple example. If they do, then it is required.

**Comment by CostaArmenUniMelb** [comment]
Hey guys,
Review the spreadsheet below and let me know if you agree with the logic. 

To summarise it, I have considered all combinations of binary operators with their own type (arithmetic, logical) and have created 3 expressions from this (let's call these First, Second and Third formulas).

**First Formula:**
This has the flat un-parenthesised form of, "expr1 binop1 expr2 binop2 expr3". For example, 2 * 3 + 4.

**Second Formula:**
This formula is the result of applying parenthesis to the RHS expression of the first formula. 
i.e. "expr1 binop1 (expr binop2 expr3)". For example, 2 * (3 + 4).

**Third formula:**
This is constructed by taking the first formula and applying precedence/associativity based parenthesis to it. There are three possible outcomes here,
1. if binop1 binds tighter than binop2 this will be '(expr1 binop1 expr2) binop2 expr3'. 
For example, 2 * 3 + 4 will become (2 * 3) + 4  as * binds tighter than +

2. if binop2 binds tighter than binop1 this will be 'expr1 binop1 (expr2 binop2 expr3)'. 
For example, 2 + 3 * 4 will become 2 + (3 * 4) as * binds tigher than +

3. if binop1 and binop2 have equal precedence this will be '(expr1 binop1 expr2) binop2 expr3' as binop1 and binop2 are left associative. 
For example, 2 * 3 / 4 will become (2 * 3) / 4 as * and / have equal precedence.

For the arithmetic case, If the second and third formula are evaluated and their values are not equal then parenthesis are required around the RHS expression. 

For the logical case, if the second and third formulas are not logically equivalent then parenthesis are required around the RHS expression.

![image](https://cloud.githubusercontent.com/assets/21965932/24825099/e800314a-1c5a-11e7-9085-1f382e7be37a.png)

**Comment by CostaArmenUniMelb** [comment]
If it helps, here is the spreadsheet.

[Parenthesis Simulation 20170408-4.xlsx](https://github.com/CostaArmenUniMelb/CantParseUs/files/907182/Parenthesis.Simulation.20170408-4.xlsx)

**macro enabled version:**
[Parenthesis Simulation 20170408-4.zip](https://github.com/CostaArmenUniMelb/CantParseUs/files/907184/Parenthesis.Simulation.20170408-4.zip)

**Comment by CostaArmenUniMelb** [comment]
Review the marking sheet before submitting

remember to add author and purpose to your lex and parser files also

**Comment by poomnewgen** [comment]
I've reviewed your excel file. It looks good and no worries, if something wrong we will see it after the test.

**Comment by poomnewgen** [comment]
It still does not work in some cases. I added some test case in logical.snack. 
e.g.        
        a:=(a+b)*c;
        a:=(a-b)*c;

**Comment by poomnewgen** [comment]
I fixed it and it passed all test cases. ready to submit

**Comment by CostaArmenUniMelb** [comment]
Sorry just saw this now. What was wrong and how did you fix it?

I'm guessing a few of the true/false's were incorrect for some operator
combinations and you found that section in the code and then replaced them
with the correct ones?

Have you submitted?

Thanks for fixing it! :) I should have tested all combinations more
thoroughly (sorry) :s

**Comment by CostaArmenUniMelb** [comment]
Ignore the above, I looked at the diff of ur latest commit and can see what
you did.

I had not considered keeping parenthesis on the LHS when they do exist

**Comment by CostaArmenUniMelb** [comment]
updated spreadsheet

![image](https://cloud.githubusercontent.com/assets/21965932/24853933/f8454dda-1e1f-11e7-96b3-44a046507ab5.png)

[Parenthesis Simulation 20170410-1.zip](https://github.com/CostaArmenUniMelb/CantParseUs/files/909533/Parenthesis.Simulation.20170410-1.zip)
